### ISSUE TITLE
[checklist][dataset page] Files in the Download section should link to the Cloud Storage and the user should be able to download them

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#111]
## Acceptance

* [x] The **Download** section should always contain data. If there is no file to be listed, it should display the text "`No resource available to download.`".
* [x] Files should be available to download and link to the Cloud Storage.

## Tasks
...

## Analysis

* Files should be available to download and link to the Cloud Storage. E.g. from https://gift-portal-git-master.datopian1.vercel.app/dataset/south-africa-national-estimates-2015-2019 one should be able to download https://gift-portal-git-master.datopian1.vercel.app/dataset/data/budget-vs-actual-national__2017.csv (which would link to the file stored in the Cloud) instead of seeing a `404` error.

**Comment by risenW** [comment]
@sglavoie Is this not duplicate to #104 ?

**Comment by sglavoie** [comment]
@risenW I think there is indeed a good amount of overlap with #104, however I couldn't successfully test with the existing datasets that this actually works. Trying to download resources from existing datasets:

![image](https://user-images.githubusercontent.com/32682903/107671509-88539400-6c59-11eb-8620-1f250b9c2660.png)

Then I was able to add a resource to `Test-Demo`, which appeared after a short delay on GitHub, though I couldn't download the resource from the dataset page:

![image](https://user-images.githubusercontent.com/32682903/107671938-fac47400-6c59-11eb-8ddf-2bc18fa3ee96.png)

![image](https://user-images.githubusercontent.com/32682903/107671997-0a43bd00-6c5a-11eb-8b17-40a3756bf46d.png)

We can confirm whether or not the second acceptance criterion has been done already (_Files should be available to download and link to the Cloud Storage_), but the first criterion (_The Download section should always contain data_) will still need to be integrated as I was seeing this in [the `Test-Demo` dataset page](https://gift-portal-git-master.datopian1.vercel.app/dataset/Test-Demo) before adding the second resource (the first one is not being shown but was showing up in the dashboard as a resource that could be removed, **although this is no longer the case as it's not in the dashboard anymore and I swear I didn't click on the red `Remove` button** :man_shrugging:):

![image](https://user-images.githubusercontent.com/32682903/107672431-7de5ca00-6c5a-11eb-8a8f-89732412164d.png)

We should expect to display some text like the following instead when there is no resource:

![image](https://user-images.githubusercontent.com/32682903/107672681-cd2bfa80-6c5a-11eb-842d-b24fb2004a6f.png)

I believe that satisfies the need to keep this issue open until we resolve/clarify those points. :slightly_smiling_face: :+1:

**Comment by sglavoie** [comment]
As a side note, you can see from the above screenshot with the name of the CSV file that the extension is being appended at the end (showing `.csv.csv` instead of `.csv` in the table). You can see the file has the right name in [the GitHub repo `Test-Demo`](https://github.com/gift-data/Test-Demo/tree/main/data):

### In the portal
![image](https://user-images.githubusercontent.com/32682903/107674568-b5ee0c80-6c5c-11eb-8e0c-238ea89d6175.png)

### On GitHub
![image](https://user-images.githubusercontent.com/32682903/107674383-89d28b80-6c5c-11eb-819f-2c433487466d.png)
