### ISSUE TITLE
[checklist][dataset page] Files in the File Preview section should always contain data and be displayed with the correct encoding

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#112]
## Acceptance

* ~~The file preview section should always contain data. If there is no file to preview, it should display the text "`No file preview available.`".~~
* ~~The content of the resources should be displayed in the correct encoding. (@sglavoie)~~

 See comment below 

## Analysis

* For @sglavoie:
  * Should present the data in the correct encoding. (E.g. broken example here https://gift-portal-git-master.datopian1.vercel.app/dataset/presupuesto-mexico-2008-2019). I.e. unicode characters showing like `Fiscalizaci\u00c3\u00b3n` in the datapackage (https://github.com/gift-data/presupuesto-mexico-2008-2019/blob/master/datapackage.json#L7905) should be displayed as `Fiscalización` instead of `FiscalizaciÃ³n`.

**Comment by risenW** [comment]
DUPLICATE: Fixed in https://github.com/datopian/gift-portal/pull/126 already
