### ISSUE TITLE
Should support pagination so that a limited number of datasets can be displayed on the home page

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#127]
When I visit the GIFT Portal, I want to see a reasonable amount of information on screen so I don't have to load all available datasets, which becomes inefficient and costly over time.

## Acceptance

* [ ] The home page of the portal displays a maximum of 15 datasets per page and shows additional pages when there are more than 15 datasets to be shown.

## Tasks

* [ ] ...

## Analysis

...

**Comment by steveoni** [comment]
@sglavoie is there a mockup of how the pagination [ button  ] will look like

**Comment by sglavoie** [comment]
@steveoni We don't have this as part of the mockups yet. The desired functionality would be as follows:

![image](https://user-images.githubusercontent.com/32682903/108452044-6c3d8d00-722d-11eb-9cd6-22bb66c65225.png)

As can be tried from here: https://www.jqueryscript.net/demo/Highly-Customizable-jQuery-Pagination-Component-jqPaginator/

But we probably want to limit the number of pages to display to 5 instead of 10 as we won't have that many.

As for the default behaviour, it would be best to avoid displaying pagination if there's only one page (≤ 15 datasets). I also think we don't have to care too much about having ellipsis (`...`) in the middle when there are many pages: just like the jQuery demo should do.

Also, if there are less than 5 pages, then we just display that number of pages (from 1 up to 4 pages). It wouldn't be super useful to have the `First` and `Last` buttons when there are only 2 pages but that would be a minor thing to take care of, we can live with that edge case. :slightly_smiling_face:

**Comment by sglavoie** [comment]
@steveoni We can drop this issue for now and consider it for **Someday Maybe** as discussed earlier today.

**Comment by sglavoie** [comment]
WONTFIX: This is not part of the original work and likely won't be done later given the relatively small number of datasets to be loaded.
