### ISSUE TITLE
Add a button in the dashboard so users can go straight to updating the metadata and don't have to upload a new resource to do that

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#132]
When I need to update metadata from a dataset, I want to be able to do this in a single step so I don't have to upload a new resource before I can access the "Provide metadata" screen of the publisher.

See related issue in publisher https://github.com/datopian/gift-publisher/issues/53, which supersedes this one.

## Acceptance

* [x] I can update the metadata of a dataset without having to upload a new resource (which happens when I click on `Edit fiscal data schema`).
* [x] The dashboard contains a link to the right of `Edit fiscal data schema` that reads `Edit metadata` and jumps straight to the "Provide metadata" screen of the flow to allow the user to only edit metadata.

https://user-images.githubusercontent.com/29900845/108365345-67f67d00-71f7-11eb-814d-a7146a98dd38.mov

**Comment by sglavoie** [comment]
FIXED: The link is showing in the dashboard and the remaining tasks are taken care of in https://github.com/datopian/gift-publisher/issues/53.

**Comment by risenW** [comment]
@sglavoie This issue is reopened, and blocked. See details here https://github.com/datopian/gift-publisher/issues/57

**Comment by risenW** [comment]
UPDATE: This is now unblocked and currently back in progress.
