### ISSUE TITLE
New datasets created should be loaded instead of showing a 404 error

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#151]
When I create a new dataset with the publisher and later look at it on the portal (index page), I want to be able to open that dataset and load its information so I can download its resources and see the remaining information specific to that dataset.

## Acceptance

* [ ] We can create new datasets and open them from the portal (index page) without seeing a 404 error.
* [ ] Older datasets (before this issue was noticed) can still be loaded from the index page.

## Tasks

* [ ] ...

**Comment by cotts** [comment]
Fixed on #94
