### ISSUE TITLE
Login with major browsers (Chrome, Firefox, Safari, Edge) should work

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#168]
When I use any major web browser, I want to be able to log in to the portal so I can use the dashboard.

## Acceptance

* [ ] Login with Firefox works just the same as with Google Chrome.
* [ ] Login with Safari works just the same as with Google Chrome.

## Tasks

* [ ] ...

## Analysis

* Couldn't log in with Safari.
* Can't log in with Firefox (tested with version 86.0.1), even in private mode with no extension enabled. Clicking on `Sign in with GitHub` redirects to https://gift-portal-git-master-datopian1.vercel.app/api/auth/signin?csrf=true while still showing the same button on the page with no indication in the JavaScript console as to what might be going wrong.
* Did not test in Edge (it is Chromium-based anyways, it's working in Brave and Chromium).

**Comment by sglavoie** [comment]
@risenW, do we have some news about this issue?

Also, related to login, the login now redirects to localhost:3000 like so when clicking on `Sign in with GitHub`:

http://localhost:3000/api/auth/callback/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=84f2b8c1f419737d6f2ecefb55fb0ca15509204a3ac5cd7fb4f6fc03409a90ad

Do you have any idea why that is the case? :thinking:

**Comment by risenW** [comment]
> @risenW, do we have some news about this issue?
> 
> Also, related to login, the login now redirects to localhost:3000 like so when clicking on `Sign in with GitHub`:
> 
> http://localhost:3000/api/auth/callback/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=84f2b8c1f419737d6f2ecefb55fb0ca15509204a3ac5cd7fb4f6fc03409a90ad
> 
> Do you have any idea why that is the case? 🤔

Is this happening in chrome as well?

**Comment by risenW** [comment]
@sglavoie We might have to change our auth library in order to fix this. I did lots of research but still can't pinpoint where this is coming from besides the fact that the lib is not compatible with non-chromium-based browsers.

**Comment by risenW** [comment]
FIXED: 
* I created a new github oauth app for production using `https://gift-portal.vercel.app/` as the call back url
* I updated next-auth in portal to not use a pop up and log in directly using github.

**Comment by sglavoie** [comment]
Thank you @risenW, that was a great solution! :smiley:  :+1:
