### ISSUE TITLE
Portal should handle empty/null values when displaying datasets

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#172]
~~When I upload a resource to a dataset, I want it to be taken care of by the Publisher/Portal when it contains empty/null values so I can continue using the Publisher/Portal without any issue.~~

## Acceptance

~~* [ ] Uploading resources containing empty/null values does not break the Publisher nor the Portal (see **Analysis** for explanations).~~
~~* [ ] Resources containing empty values **are to be accepted** by the Publisher (we only validate the data schema, not the content of the resources).~~
~~* [ ] The file preview in the page of a dataset does not break in the presence of empty/null values.~~
* [x] Portal can handle display of datasets with missing values/incomplete data package **Done** See #173 

## Tasks

~~* [ ] Test against adding resources that contain empty/null values and handle those files adequately.~~
~~* [ ] Ensure that the file preview in the page of a dataset will not break in the presence of empty/null values.~~
* [*] Properly handle empty/null error during build
# Analysis

After having uploaded files containing empty values, it seems that this was the direct cause of the server breakdown at https://gift-portal.vercel.app/ :

![image](https://user-images.githubusercontent.com/32682903/114589893-bcddcf00-9c4d-11eb-9545-4ee4a9d0d4b8.png)

The list of problematic files is as follows:
```
costa-rica-presupuesto-egresos-2017/data/egreso2017ene_dic__2017.csv
costa-rica-presupuesto-egresos-2017/data/egreso2017ene_dic.csv
costa-rica-presupuesto-egresos-2018/data/egreso2018ene_dic__2018.csv
costa-rica-presupuesto-egresos-2018/data/egreso2018ene_dic.csv
costa-rica-presupuesto-egresos-2019/data/egreso2019ene_dic__2019.csv
costa-rica-presupuesto-egresos-2019/data/egreso2019ene_dic.csv
costa-rica-presupuesto-egresos-2020/data/egreso2020ene_feb2__2020.csv
costa-rica-presupuesto-egresos-2020/data/egreso2020ene_feb2.csv
croatia-budget-spending/data/croatia-budget-spending.csv
croatia-budget-spending/data/croatia-budget-spending__2018.csv
croatia-budget-spending/data/croatia-budget-spending__2017.csv
croatia-budget-spending/data/croatia-budget-spending__2016.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2010.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2015.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2018.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2019.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2017.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2020.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2008.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2009.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2014.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2013.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2016.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2011.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2012.csv
```

It was posssible to upload pretty much all of them before the error manifested. Croatia and Costa Rica were successfully uploaded but the server got stuck when updating Mexico as can be seen at https://github.com/gift-data/mexico/commits/main (latest changes that were made before the crash).

We have no control whatsoever over the content of the datasets, so the Publisher must support handling null/empty values (i.e. should not cause trouble and the file should be accepted/uploaded as it is without crashing the Portal).

Screenshot from the Vercel logs:

<img width="1114" alt="Screen Shot 2021-04-13 at 10 08 12 AM" src="https://user-images.githubusercontent.com/32682903/114590393-54dbb880-9c4e-11eb-93d5-18c34ee96ce9.png">

**Comment by risenW** [comment]
@sglavoie  I fixed the error and updated the issue accordingly.

**Comment by sglavoie** [comment]
@risenW I am re-opening as I see that indeed we don't crash the server as such anymore, but the data still needs to be uploaded, used and displayed. As long as the schema matches, we should be able to work with any uploaded resources regardless of missing fields.

The problem occurred once more after uploading the year 2018 for Mexico ([resource available here](https://storage.googleapis.com/gift-datasets/gift-data/MDEwOlJlcG9zaXRvcnkzNTk0NDYyODM%3D/fd736172e7d5a7d3d5e5aaef1e21a5b5cc86dfbd3e0c5ae67d487b8e9bd0e69b), ~156MB)

This is how it shows in the dashboard:
![image](https://user-images.githubusercontent.com/32682903/115236513-12e4c380-a0e1-11eb-87a4-44ce3e340168.png)

Even though it has years 2008–2018 uploaded at https://github.com/gift-data/mexico/tree/main/data, the state of the dataset is broken (the link is in fact https://gift-portal.vercel.app/admin/publisher/undefined from the dashboard instead of https://gift-portal.vercel.app/admin/publisher/mexico):
![image](https://user-images.githubusercontent.com/32682903/115238189-05303d80-a0e3-11eb-9b08-6070ae02d995.png)

I don't know yet what the exact issue is as you'll see that this other dataset, https://gift-portal.vercel.app/dataset/mexico2 and shown at https://gift-portal.vercel.app/dataset/mexico2, contains years 2018 and 2019, so it's not specific to that file although it just happened that it failed twice after I uploaded 2018 (the first time being when it crashed and the second time the description I'm adding to this comment).

**Comment by sglavoie** [comment]
I tried re-uploading all files again and it failed at the same point, which leads me to believe that it might have something to do with this: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/limits-for-viewing-content-and-diffs-in-a-repository#diff-limits

It says:

> **No single file's diff may exceed 20,000 lines** that you can load or 1 MB of raw diff data. [...]

This would be a weird coincidence for sure, but it does happen every time the `datapackage.json` goes a bit above 20,000 lines! In fact, on GitHub, it consistently fails with the syntax highlighting near the end of the file:

![image](https://user-images.githubusercontent.com/32682903/115458991-20d33b00-a1ec-11eb-806f-d28912ec29b9.png)

Then, if you `console.log` that locally, the content of the JSON file stops exactly where the syntax highlighting stops working on GitHub:

![image](https://user-images.githubusercontent.com/32682903/115459296-80c9e180-a1ec-11eb-959e-3e94c4375b04.png)

So maybe the solution is indeed reading the raw file `datapackage.json` (e.g. https://raw.githubusercontent.com/gift-data/mexico5/main/datapackage.json), I'm not sure. The `repo` object is definitely failing to contain all the JSON once there are more than 20,000 lines in `datapackage.json`. The fact that it seems to happen with any file would confirm that the issue is not with the actual files, but with the size of the JSON file (which I've validated online with something like https://jsonformatter.curiousconcept.com/ just in case and it's valid despite its length). I will have to generate new test files with at least as many columns as those in the Mexico dataset to confirm that hypothesis, but it looks like a possible path forward to debug this further :slightly_smiling_face:.

**Comment by risenW** [comment]
@sglavoie Thanks for the well-researched issue. I do think the limit is a valid reason. And we can definitely try reading files directly from the raw datapackage. I'll try this on my end and let you know.

**Comment by sglavoie** [comment]
Thanks @risenW! Looking at your PR, it looks like we might go for that solution even though there will now be a delay when refreshing the application. I think it's a great compromise. :+1:
