### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#30]
## Acceptance

* [x] linting setup - **Done**
* [x] linting run as part of github actions - **Done**
* [x] datopian playbook updated with template code (or links therein) for settings this (e.g. a lint config file, sample github actions code) in https://playbook.datopian.com/style-guide/javascript/#_2-linting - **Done [Here](https://github.com/datopian/playbook/pull/10)**

**Comment by cotts** [comment]
I've added the pull request for the playbook configuration [here](https://github.com/datopian/playbook/pull/10)
