### ISSUE TITLE
Dynamic route to dataset Publisher

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#58]
I want to be able to access publisher per dataset via `admin/publisher/id`

## Acceptance

* [x] Ensure the dynamic route `admin/publisher/id` is working and file upload is working **DONE** - https://github.com/datopian/gift-portal/blob/master/pages/admin/publisher/%5Bid%5D.js

## Task

* [x] move embedding publisher app to route `admin/publisher/id` **DONE** - https://github.com/datopian/gift-portal/blob/master/pages/admin/publisher/%5Bid%5D.js

**Comment by risenW** [comment]
@steveoni Can you update the acceptance criteria and then close this issue, since it has been fixed.
