### ISSUE TITLE
Shared state - research

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#71]
# Update: This is being implemented in #75 
We want a certain global shared state in gift-portal; to which data can be passed down across all pages and also global state can be updated on any page and then reflected across all pages.

# Shared state - research

**@steveoni** to start working on this once we have a working demo we can show the client on Friday, with **@thadeu**'s help if necessary.

We want certain global shared state ... namely
  
* MetaStore DB with its catalog of datasets
  * We can try to use the https://github.com/typicode/lowdb
* Permissions DB

Client code => MetaStore => lookup in Cache OR go and load (from remote API)

* What is best approach in React to manage our common global state?
  * https://github.com/datopian/portal.js/issues/18
  * https://github.com/datopian/portal.js/issues/24

From issue 18

How should we get (meta)data / content? What is the "data layer" for this system?

The content fetching divides into two parts:

```mermaid
graph LR

remote[Remote e.g. CKAN API] --fetchers--> localdb[Local DB Cache]
localdb --common api--> render[Renderer]
```

* Want a common API / structure for local DB so that renderers have a simple interface and the complexity of fetchers is hidden from them. Options:
  * redux
  * graphql based
* **SUMMARY**: atm we are strongly inclining to graphql based approach. (see below for reasoning)
* fetchers will always be somewhat bespoke

```mermaid
graph TD

nextjs[Portal code e.g. dataset page or /api/dataset]

nextjs --> localdb[MetaStore - local DB]
localdb --> backend[Backend e.g. github]
```

Code e.g. displaying a dataset page ...

```
MetaStore.fetch(datasetId)

MetaStore.get => either looks up in local cache or loads from github 
                 and stores into cache and returns
```

Code in /api/dataset/{id}

```javascript=
MetaStore.save/put(datasetId, descriptor)

// What does this do behind the scenes?
// 
// 1. Updates the local cache
// 2. Saves to backend e.g. using our metastore-lib-js it saves to github
```

###  Shared State Using react ContextApi and UseReducer

 We can have a global variable which can be passed to all pages using `React ContextApi` and manage different state with the help of `React useReducer`.

In Next.js global variable can be passed down and access by all pages via `pages/_app.js` using ContextApi

```js
// _app.js
import StoreContext from '../lib/context';
function MyApp({ Component, pageProps }) {
  const global = "Global variable"

  return (
    <StoreContext.Provider  value={{global}}>
      <Component {...pageProps} />
    </StoreContext.Provider>
  
  )
}
```
And such global variable  can be accessed on any page via `React useContext`

```js

//page1.js

import { useContext } from 'react';
import StoreContext from '../lib/context';

function Page1() { 
   const { global } = useContext( StoreContext );
  return <div> {global } </div>

}

export default Page1

```

while `../lib/Context` contains the context Provider

```js
import React from 'react';

const StoreContext = React.createContext();

export default StoreContext
```

To update the global variable we can always pass down a global state using the same approach 

```js
// _app.js
import StoreContext from '../lib/context';
import {useState } from 'react';

function MyApp({ Component, pageProps }) {
  const  [ global, setGlobal ] = useState("I'm global")
 

  return (
    <StoreContext.Provider  value={{global, setGlobal}}>
      <Component {...pageProps} />
    </StoreContext.Provider>
  
  )
}
```

The global state can be updated on any page

```js

//page1.js

import { useContext, useEffect  } from 'react';
import StoreContext from '../lib/context';

function Page1() { 
   const { global , setGlobale} = useContext( StoreContext );
   useEffect(() => {
     setGlobal('new update")
   },[global]);

  return <div> {global } </div>

}

export default Page1

```

**SHORTCOMINGS**

This approach handles next.js app pages as a single page application, in which all pages are like components. Hence in order not to lose state changes, all pages must be visited via `next/Link' i.e

```js
//page 2.js

import Link from 'next/Link';

function Page2() {

 return <Link href='/page1'><a>Page 1</a></Link>

}

```
That is if any page is reloaded new update is gone (we are left with the default state).

**To use Approach for the gift Portal app**

1. Have a global variable (empty data store) passed down via `_app..js`
2. have a data **fetching page**, which can be the home page, from this page the `empty data store` is updated, Hence with this new update push to Github can always be shown
3. this data can be accessed across every other page, 

#### What if users reload the page? (base on the shortcomings)

We can always pass down a `local db` via the  context api 

#### How can we make the `data fetching page` fetch data only when there is a new update?

Since new updates occur during publisher flow, we can pass a state down to the publisher page, which can be updated when never there is a new publish. 

This state can always be check before fetching from Github

```js
.....
function DataPage() {
 useEffect(() => {
  // fetch from github
 }, [PublisherState]); //check if publisher state is updated whenever the page is visited
 ......

}
```
This will work provided the page is not reloaded but visited via `next/Link`.

To prevent this, On the publisher page, we can store a  notified variable in the `local db`; to notify if there is a change on the Data page:

Refrence

https://github.com/vercel/next.js/tree/canary/examples/with-context-api

**Comment by risenW** [comment]
@steveoni Is this different from the caching mechanism I have been researching as well? It looks similar. 
Do you plan to store github queries using the context API as well?

**Comment by rufuspollock** [comment]
@risenW @steveoni have either of you spoken yet to @anuveyatsu and discussed how we used apollo in portal.js?
