### ISSUE TITLE
Pass Dataset Id instead of Repo name to publisher

### ISSUE THREAD

**Issue by risenW** [datopian/gift-portal#77]
The dataset Id passed to the publisher app should be the repository unique ID provided by Github, and not the repository name. 

## Acceptance
* [  ] The parameter passed to the `/admin/publisher/[id]` is the repository id and not the repository name 

## Task
* [  ] Update query method [here](https://github.com/datopian/gift-portal/blob/d083291285/db/query.js) to return repository ID 
* [  ] Update function [here](https://github.com/datopian/gift-portal/blob/d083291285db1c57f2715ccad41fcedc6177b3de/pages/dataset/%5Bdatasetid%5D.js#L215) to pass repo ID

**Comment by rufuspollock** [comment]
@risenW strictly what we want is that *in* storage (and storage only) we use the git repo id to generate the path.

**Comment by rufuspollock** [comment]
I think this is now DUPLICATE / OBSOLETE due to #79
